#!/usr/bin/python3
import os
import pathlib
import shutil

dir_path = pathlib.Path(os.path.dirname(os.path.realpath(__file__)))
tmp_path = dir_path.joinpath('last_pid.tmp')
if not tmp_path.exists():
    template_path = dir_path.joinpath('last_pid.template')
    shutil.copyfile(template_path, tmp_path)
with open(tmp_path, 'r+') as f:
    pid = int(f.readline())
    pid += 1
    f.seek(0)
    f.write(str(pid))
    print(pid)