hpc_account:
  username: not_the_real_one
  password: not_the_real_one
  group: not_the_real_one
  reservation_name: not_the_real_one

bifrost_analyses:
  bifrost_min_read_check:
    version: 2.2.8
    type: classic  # This is not used for the moment, but we might need a new component type in the future.

  bifrost_whats_my_species:
    version: 2.2.11__171019
    type: classic

  bifrost_assemblatron:
    version: 2.2.15
    type: classic

  bifrost_ssi_stamper:
    version: 2.2.9
    type: classic
  
  bifrost_cge_mlst:
    version: 2.2.4
    type: classic

  bifrost_seqsero:
    version: 0.0.2
    type: classic
