bifrost_components:
    - identifier: bifrost_min_read_check
      version: 2.2.8

    - identifier: bifrost_whats_my_species
      version: 2.2.11__171019

    - identifier: bifrost_assemblatron
      version: 2.2.15

    - identifier: bifrost_ssi_stamper
      version: 2.2.9
    
    - identifier: bifrost_cge_mlst
      version: 2.2.4

    - identifier: bifrost_seqsero
      version: 0.0.2
