version: "3.9"
services:
  analysis_control:
    build: .
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: $HOST/home/finn/species
        target: /chewie_data
      - type: bind
        source: $HOST/home/finn/config.yaml
        target: /container/location