version: "3.9"
services:
  analysis_control:
    build: .
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: $AC_CONFIG
        target: /app/config.yaml
      - type: bind
        source: $CHEWIE_DATA
        target: /chewie_data
    environment:
      - MONGO_CONN=$MONGO_CONN
      - HPC_HOSTNAME=$HPC_HOSTNAME
      - HPC_PORT=$HPC_PORT
      - HPC_USERNAME=$HPC_USERNAME
      - HPC_PASSWORD=$HPC_PASSWORD
