version: "3.9"
services:
  analysis_control:
    build: .
    ports:
      - 8000:80
    volumes:
      - type: bind
        source: $AC_CONFIG
        target: /config.yaml
      - type: bind
        source: $CHEWIE_DATA
        target: /chewie_data