hpc:
  command_prefix: qsub -A fvst_ssi_dtu -W group_list=fvst_ssi_dtu -l nodes=1:ppn=40,advres=fvst_ssi_dtu_wiki_fodevarestyrelsen.16

bifrost_use_hpc:
  true

bifrost_launch_script:
  /home/finn/.local/bin/launch_bifrost.sh

bifrost_analyses:
  bifrost_min_read_check:
    type: bifrost_component
    version: 2.2.8

  bifrost_whats_my_species:
    type: bifrost_component
    version: 2.2.11__171019

  bifrost_assemblatron:
    type: bifrost_component
    version: 2.2.15

  bifrost_ssi_stamper:
    type: bifrost_component
    version: 2.2.9
  
  bifrost_cge_mlst:
    type: bifrost_component
    version: 2.2.4

  bifrost_seqsero:
    type: bifrost_component
    version: 0.0.2

species:
  Salmonella_enterica:
    cgmlst: Salmonella_enterica/output/cgmlst