hpc_account:
  username: not_the_real_one
  password: not_the_real_one
  group: not_the_real_one
  reservation_name: not_the_real_one

bifrost_analyses:
  bifrost_min_read_check:
    type: bifrost_component
    version: 2.2.8

  bifrost_whats_my_species:
    type: bifrost_component
    version: 2.2.11__171019

  bifrost_assemblatron:
    type: bifrost_component
    version: 2.2.15

  bifrost_ssi_stamper:
    type: bifrost_component
    version: 2.2.9
  
  bifrost_cge_mlst:
    type: bifrost_component
    version: 2.2.4

  bifrost_seqsero:
    type: bifrost_component
    version: 0.0.2

